*** Variables ***
${scrollBar} =        //android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.View/android.widget.FrameLayout/android.widget.RelativeLayout/android.widget.ScrollView
${topicDropdown} =    //android.widget.FrameLayout/android.widget.ListView
${topicDetail} =      //*[@resource-id="com.kiminonawa.mydiary:id/LL_topic_detail_content"]
${inputField} =       //*[@resource-id="com.kiminonawa.mydiary:id/EDT_topic_detail_title"]
${contacts} =         //android.widget.FrameLayout/android.widget.ListView/android.widget.CheckedTextView[1]
${diary} =            //android.widget.FrameLayout/android.widget.ListView/android.widget.CheckedTextView[2]
${memo} =             //android.widget.FrameLayout/android.widget.ListView/android.widget.CheckedTextView[3]
${okButton} =         //*[@resource-id="com.kiminonawa.mydiary:id/But_topic_detail_ok"]